# Generated by Django 2.2.13 on 2020-10-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
